name: Dev Glimpse Client Deploy

on:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Dynamically set MY_DATE environment variable
        run: echo "MY_DATE=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.17.0

      - name: Install Client-Server
        run: npm ci

      - name: Compile Client-Server
        run: npm run build

      # AWS 자격 증명 수행
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download .env file from S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} s3://${{secrets.AWS_S3_BUCKET_NAME}}/${{secrets.PROD_DEPLOY_PROJECT_NAME}}/.env .env

      - name: Make a zip file
        run: |
          zip -r ./$GITHUB_SHA.zip . -x "node_modules/*" "coverage/*" "src/*" "test/*" "README.md" "*.git*" "common/*" "tsconfig.json" "tsconfig.build.json"
        shell: bash

      # zip 파일 S3 업로드
      - name: Upload to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./$GITHUB_SHA.zip s3://${{secrets.AWS_S3_BUCKET_NAME}}/${{secrets.PROD_DEPLOY_PROJECT_NAME}}/snapshot/${{ env.MY_DATE }}.zip

      # 코드 배포
      - name: Code Deploy
        run: aws deploy create-deployment
          --application-name ${{secrets.AWS_CODEDEPLOY_APPLICATION_NAME}}
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name ${{secrets.PROD_AWS_CODEDEPLOY_DEPLOYMENT_GROUP_NAME}}
          --s3-location bucket=${{secrets.AWS_S3_BUCKET_NAME}},bundleType=zip,key=${{secrets.PROD_DEPLOY_PROJECT_NAME}}/snapshot/${{ env.MY_DATE }}.zip
